# Generated by Django 2.2.7 on 2019-12-14 07:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('content', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(4, 'Note content is too short.')])),
            ],
            options={
                'ordering': ('updated',),
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(4, 'Subject name is too short.')])),
                ('description', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(4, 'Subject description too short.')])),
            ],
            options={
                'ordering': ('updated',),
            },
        ),
    ]
