export const FETCH_SUBJECTS_REQUEST = 'FETCH_SUBJECTS_REQUEST';
export const FETCH_SUBJECTS_SUCCESS = 'FETCH_SUBJECTS_SUCCESS';
export const FETCH_SUBJECTS_FAILURE = 'FETCH_SUBJECTS_FAILURE';

export const SEARCH_SUBJECTS_REQUEST = 'SEARCH_SUBJECTS_REQUEST';
export const SEARCH_SUBJECTS_SUCCESS = 'SEARCH_SUBJECTS_SUCCESS';
export const SEARCH_SUBJECTS_FAILURE = 'SEARCH_SUBJECTS_FAILURE';

export const FETCH_SUBJECT_REQUEST = 'FETCH_SUBJECT_REQUEST';
export const FETCH_SUBJECT_SUCCESS = 'FETCH_SUBJECT_SUCCESS';
export const FETCH_SUBJECT_FAILURE = 'FETCH_SUBJECT_FAILURE';

export const CREATE_SUBJECT_REQUEST = 'CREATE_SUBJECT_REQUEST';
export const CREATE_SUBJECT_SUCCESS = 'CREATE_SUBJECT_SUCCESS';
export const CREATE_SUBJECT_FAILURE = 'CREATE_SUBJECT_FAILURE';

export const EDIT_SUBJECT_REQUEST = 'EDIT_SUBJECT_REQUEST';
export const EDIT_SUBJECT_SUCCESS = 'EDIT_SUBJECT_SUCCESS';
export const EDIT_SUBJECT_FAILURE = 'EDIT_SUBJECT_FAILURE';

export const DELETE_SUBJECT_REQUEST = 'DELETE_SUBJECT_REQUEST';
export const DELETE_SUBJECT_SUCCESS = 'DELETE_SUBJECT_SUCCESS';
export const DELETE_SUBJECT_FAILURE = 'DELETE_SUBJECT_FAILURE';

export const SUBJECTS_PAGINATION_PROP_CHANGE =
  'SUBJECTS_PAGINATION_PROP_CHANGE';
